services:
  # Backend service
  - type: web
    name: xenith-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your MongoDB connection string as an environment variable
    # You'll need to add MONGODB_URI in Render dashboard

  # Frontend service (if you want to deploy separately)
  # - type: web
  #   name: xenith-frontend
  #   env: static
  #   plan: free
  #   buildCommand: cd frontend && npm install && npm run build
  #   staticPublishPath: frontend/build
